export const TASKS = {
  diario: {
    label: "Diario", xp: 3, reset: "se reinicia cada día",
    items: [
      { text: "BAÑOS", steps: ["Sacudir Paredes","Cambiar Bolsa de Papeles Higiénicos","Barrer Piso","Desinfectar inodoro","Trapear Piso"] },
      { text: "DUCHAS", steps: ["Sacudir paredes","Barrer Piso","Restregar el Piso con Jabón","Trapear el Piso"] },
      { text: "LAVAMANOS", steps: ["Sacudir Lámparas","Lavar Mesón y lavamanos","Revisar Jaboneras"] },
      { text: "LAVANDERIA", steps: ["Organizar y Limpiar estantes y cajonera","Escoba y Trapero Colgados","Limpiar Lavadora","Lavar Fundas y Toallas"] },
      { text: "BODEGA", steps: ["Mantener herramientas organizadas","Barrer Piso"] },
      { text: "COCINA", steps: ["Organizar Utensilios","Limpiar y Organizar Nevera","Limpiar y Organizar Cajoneras","Limpiar mesón y Estufa","Barrer Piso","Trapear Piso","Sacar Basura Orgánica"] },
      { text: "SALA", steps: ["Sacudir y Barrer Coworking","Barrer y Organizar Zapatero","Organizar Matts y Gym","Organizar y Barrer Recepción","Sacudir Puffs","Sacudir Tapete","Sacudir Mueble","Limpiar Mesa","Regar Plantas","Sacudir Hamacas","Barrer Sala Completa","Limpiar Espejo","Llenar Filtros de Agua"] },
    ],
  },
  semanal: {
    label: "Semanal", xp: 8, reset: "reporte cada lunes",
    items: [
      { text: "LIMPIAR TECHO DE LA SALA" },
      { text: "LAVAR NEVERA" },
      { text: "REVISAR COMEJÉN" },
      { text: "REVISAR PRODUCTOS DE ASEO", steps: ["Jabón Líquido","Límpido","Soflán","Jabón para Platos","Papel Higiénico","Bolsas para Papeles","Vinagre","Dispensadores de Baño"] },
      { text: "REVISAR SABANAS Y TOALLAS" },
      { text: "REVISAR ESTADO DE HABITACIONES" },
      { text: "LIMPIEZA FULL DE COCINA" },
      { text: "QUEMAR BASURA" },
    ],
  },
  quincenal: {
    label: "Quincenal", xp: 12, reset: "cada 15 y 30 del mes",
    items: [
      { text: "ASEO GENERAL" },
      { text: "LAVADO PROTECTOR MUEBLE" },
      { text: "LAVADO DE PUFF" },
      { text: "LIMPIAR BOMBILLOS Y LUCES" },
      { text: "REVISAR LLAVES Y CANDADO" },
      { text: "INVENTARIO DE SÁBANAS" },
      { text: "LAVAR FILTROS DE AGUA" },
      { text: "LAVAR HAMACAS" },
      { text: "LAVAR TOLDILLOS" },
    ],
  },
  mensual: {
    label: "Mensual", xp: 15, reset: "cada 30 o última semana del mes",
    items: [
      { text: "LIMPIAR CANALETAS" },
      { text: "REVISAR VENTILADORES" },
      { text: "VOLTEAR LOS COLCHONES" },
      { text: "REVISAR ALMOHADAS" },
      { text: "REVISAR CUERDAS HAMACA" },
      { text: "FUMIGAR HOSTAL" },
      { text: "COMPRAR PRODUCTOS DE ASEO" },
      { text: "COORDINAR SALIDA DE VIDRIO Y LATAS CON ALPIDIO" },
      { text: "INVENTARIO HERRAMIENTAS" },
      { text: "MANTENIMIENTO DE PUERTAS Y CHAPAS" },
      { text: "REVISAR TUBERÍAS DE LAS DUCHAS Y BAÑOS" },
    ],
  },
  trimestral: {
    label: "Trimestral", xp: 20, reset: "junio · septiembre · diciembre",
    items: [
      { text: "REVISAR ROUTER Y MÁQUINAS ELÉCTRICAS" },
      { text: "REVISAR FUNCIONAMIENTO DE LAVADORA" },
      { text: "REVISAR ESTUFA" },
      { text: "MANTENIMIENTO DE VENTILADORES" },
      { text: "DEPURAR BODEGA" },
      { text: "Mantenimiento profundo de la casa completa" },
      { text: "LAVAR TANQUES DE AGUA" },
    ],
  },
};
